config/routes.rb
Crm::Application.routes.draw do

  def set_route(pp, ps, c)
    match "#{pp}(.:format)",   :controller => c,  :action => 'index',     :via => :get,   :as => c
    match "#{pp}(.:format)",   :controller => c,  :action => 'create',    :via => :post,  :as => c
    match "#{ps}/new(.:format)",         :controller => c,  :action => 'new',       :via => :get,   :as => "new_#{c.singularize}"
    match "#{ps}/:id/edit(.:format)",    :controller => c,  :action => 'edit',      :via => :get,   :as => "edit_#{c.singularize}"
    match "#{ps}/:id(.:format)",         :controller => c,  :action => 'update',    :via => :put,   :as => "#{c.singularize}"
    match "#{ps}/:id(.:format)",         :controller => c,  :action => 'destroy',   :via => :delete, :as => "#{c.singularize}"
  end

  match 'attachment/:id(.:format)', to: 'attachments#destroy', via: :delete, as: :attachment

  match 'configuration', :controller => 'settings', :action => 'index', :via => :get, :as => 'settings'
  match 'configuration/update', :controller => 'settings', :action => 'update', :via => :post, :as => 'settings'

  match 'extractions/select_param_accounts', :controller=>'extractions', :action => 'select_param_accounts'
  match 'extractions/comptes', :controller=>'extractions', :action => 'accounts', :as => :csv, :via => :post
  match 'extractions/select_param_contacts', :controller=>'extractions', :action => 'select_param_contacts'
  match 'extractions/contacts', :controller=>'extractions', :action => 'contacts', :as => :csv

  match 'extractions/csv_backup', :controller=>'application', :action => 'send_csv_backup_file'
  match 'extractions/yaml_backup', :controller=>'application', :action => 'send_yaml_backup_file'

  match 'type-evenements(.:format)', to: 'eventTypes#index', via: :get, as: :event_types
  match 'type-evenements(.:format)', to: 'eventTypes#create', via: :post, as: :event_types
  match 'type-evenement/new(.:format)', to:'eventTypes#new', via: :get, as: :new_event_type
  match 'type-evenement/:id/edit(.:format)', to: 'eventTypes#edit', via: :get, as: :edit_event_type
  match 'type-evenement/:id(.:format)', to: 'eventTypes#update', via: :put, as: :event_type
  match 'type-evenement/:id(.:format)', to: 'eventTypes#destroy', via: :delete, as: :event_type

  match 'modele-devis(.:format)', to: 'quotationTemplates#index', via: :get, as: :quotation_templates
  match 'modele-devis(.:format)', to: 'quotationTemplates#create', via: :post, as: :quotation_templates
  match 'modele-devis/new(.:format)', to:'quotationTemplates#new', via: :get, as: :new_quotation_template
  match 'modele-devis/:id/edit(.:format)', to: 'quotationTemplates#edit', via: :get, as: :edit_quotation_template
  match 'modele-devis/:id(.:format)', to: 'quotationTemplates#update', via: :put, as: :quotation_template
  match 'modele-devis/:id(.:format)', to: 'quotationTemplates#destroy', via: :delete, as: :quotation_template

  resources :quotationLines

  set_route('devis', 'devis', 'quotations')
  match '/devis/filter(.:format)', :controller => 'quotations', :action => 'filter', :via => :get, :as => "filter_quotations_index"
  match '/devis/update_contact_select/:id', :controller=>'quotations', :action => 'update_contact_select'
  match '/devis/update_opportunity_select/:id', :controller=>'quotations', :action => 'update_opportunity_select'
  match '/devis/companies(.:format)', to: 'quotations#get_companies', via: :get
  match '/devis/contacts(.:format)', to: 'quotations#get_contacts', via: :get
  get '/devis/:id(.:format)', :controller => 'quotations', :action => 'show'
  set_route('relations', 'relation', 'relations')
  set_route('documents', 'document', 'documents')

  devise_for :user, :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' }, :controllers => { :registrations => 'registrations' }, :skip => [ :registrations, :sessions ]
  devise_scope :user do
    get '/login(.:format)',        :to => 'devise/sessions#new',        :as => :alt_new_user_session
	get '/user/login(.:format)',        :to => 'devise/sessions#new',        :as => :new_user_session
	post '/user/login(.:format)',       :to => 'registrations#session_new', :as => :user_session
    match '/user/logout(.:format)',          :to => 'devise/sessions#destroy', :via => Devise.mappings[:user].sign_out_via, :as => :destroy_user_session

    match '/users(.:format)', :controller => 'registrations', :action => 'index', :via => :get, :as => 'users'
    match '/user/:id/edit(.:format)', :controller => 'registrations', :action => 'edit', :via => :get, :as => 'edit_user'
    match '/user/new', :controller => 'registrations', :action => 'new', :via => :get, :as => 'new_user'
    match '/user/:id', :controller => 'registrations', :action => 'update', :via => :put, :as => 'user'
    match '/user/:id', :controller => 'registrations', :action => 'destroy', :via => :delete, :as => 'user'
    match '/users', :controller => 'registrations', :action => 'create', :via => :post, :as => 'users'
  end

  set_route('opportunites', 'opportunite', 'opportunities')
  match '/opportunites/update_contact_select/:id', :controller=>'opportunities', :action => 'update_contact_select'
  match '/opportunites/filter(.:format)', :controller => 'opportunities', :action => 'filter', :via => :get, :as => "filter_opportunity_index"

  set_route('origines', 'origine', 'origins');

  set_route('activites', 'activity', 'activities');

  set_route('categories_contrat', 'categorie_contrat', 'contract_categories');

  set_route('avancements_campagne', 'avancement_campagne', 'campaign_completed_stages');

  set_route('resultats_campagne', 'resultat_campagne', 'campaign_result_stages');

  set_route('campagnes', 'campagne', 'campaigns');

  set_route('contrats', 'contract', 'contracts');
  match '/contrats/filter(.:format)', :controller => 'contracts', :action => 'filter', :via => :get, :as => "filter_contracts_index"

  set_route('tags', 'tag', 'tags');

  set_route('modes_paiement', 'payment_mode', 'payment_modes');

  set_route('conditions_reglement', 'payment_term', 'payment_terms');

  match 'taches/update_contact_select/:id', :controller=>'tasks', :action => 'update_contact_select'

  set_route('taches', 'tache', 'tasks')
  match '/taches/filter(.:format)', :controller => 'tasks', :action => 'filter', :via => :get, :as => "filter_tasks_index"
  match '/tache/:id/finished', :controller=>'tasks', :action=>'finished', :as=>"finished_task"

  set_route('categories_compte', 'account_category', 'account_categories');

  set_route('type_evenement_email', 'mail_event_type', 'mail_event_types');
  
  match 'comptes/extract', controller: 'accounts', action: 'extract'
  match 'comptes/delete_tag', :controller=> 'accounts', :action =>'delete_tag'
  match 'comptes/doublons', controller: 'accounts', action: 'duplicates', :as => 'duplicate_accounts'
  match 'compte/:id/fusion/:id_to_merge', controller: 'accounts', action: 'merge', :via => :patch, :as => "merge_accounts"
  resources :accounts, :path => 'compte' do
    collection do
      get 'search'
      get 'search_tel'
      get 'update_tags'
      get 'filter'
      post 'add_tag'
    end
    resources :events, path: 'evenements'
    resources :tasks, path: 'taches'
    resources :opportunities, path: 'opportunites'
    resources :quotations, path: 'devis'
    resources :tags, path: 'tags'
    resources :documents, path: 'documents'
    resources :relations, path: 'relations'
    resources :contacts
    resources :contracts, path: 'contrats'
  end
  match 'comptes', :controller => 'accounts', :action => 'index'

  set_route('evenements', 'evenement', 'events')

  set_route('contacts', 'contact', 'contacts');
  match 'contacts/extract', controller: 'contacts', action: 'extract'
  match 'contacts/search(.:format)', :controller => 'contacts', :action => 'search', :via => :get, :as => "search_contact_index"
  match 'contacts/filter(.:format)', :controller => 'contacts', :action => 'filter', :via => :get, :as => "search_contact_index"

  root :to => 'home#index'

  match 'reporting', :controller => 'home', :action => 'reporting'

  match 'search_by_phone/:phone_number', :controller => 'home', :action => 'search_by_phone'

  resources :about

  put "webmail_connections/update"
	get "webmail_connections/edit"
	get "webmail_connections/check"

  set_route('emails', 'email', 'emails')
  get "emails/convert"
  put "email/update"

	set_route('notifications', 'notification', 'notifications')

  resources :imports do
    new do
      post 'accounts'
      post 'contacts'
    end
  end
  match 'download', :controller => 'imports', :action => 'download'

  resources :import_accounts
  match 'import_accounts/importing', :controller => 'import_accounts', :action => 'importing_accounts'
  match 'import_accounts/recalculate_duplicates', :controller=>'import_accounts', :action=>'recalculate_duplicates'
  match 'destroy_all_invalids_accounts', :controller=>'import_accounts', :action=>'destroy_all_invalids'

  resources :import_contacts
  match 'import_contacts/importing', :controller => 'import_contacts', :action => 'importing_contacts'
  match 'import_contacts/recalculate_duplicates', :controller=>'import_contacts', :action=>'recalculate_duplicates'
  match 'destroy_all_invalids_contacts', :controller=>'import_contacts', :action=>'destroy_all_invalids'

end

app/controllers/notifications_controller.rb
# encoding: utf-8
class NotificationsController < ApplicationController

  def index
		@emails = Email.where("user_id = ?", current_user.id).limit(5).order("id")
		@tasks = Task.where("user_id =? AND statut IN ('En cours','A faire')", current_user.id).order("statut ASC, priority DESC, term DESC").limit(5)

		# On récupère les paramètres du serveur mail
	    if (WebmailConnection.all.length == 1)
		    @connection = WebmailConnection.first
		else
			@connection = WebmailConnection.new
		end
  end

end

app/helpers/notifications_helper.rb
module NotificationsHelper
end

app/views/notifications/_emails.html.erb
<div class="container-fluid">
  <table class="table table-bordered table-striped table-hover">
    <thead>
		<tr>
			<th colspan="8">
				<h3 class="pull-left">Messages à traiter</h3>
			</th>
		<tr/>
    <tr>
			<th class="text-center">Contact</th>
			<th class="text-center">Compte</th>
			<th class="text-center">Objet</th>
			<th class="text-center">Aperçu du contenu</th>
			<th class="text-center">PJ</th>
			<th class="text-center">Date</th>
			<th class="text-center">Action</th>
    </tr>
    </thead>
    <tbody>
        <% @emails.each do |email| %>
				<% if email.is_convertible_to_events? %>
          <tr class="success">
            <td class="text-center"><%=email.contacts.first.full_name unless email.contacts.empty? %></td>
            <td class="text-center"><%=email.accounts.first.company%></td>
        <% else %>
          <tr>
            <td class="text-center"><%=email.to.join("\n")%></td>
            <td class="text-center"></td>
        <%end%>
            <td class="text-center"><%=email.object%></td>
            <td class="text-center"><%=email.content.truncate(40) unless email.content.nil? %></td>
            <td class="text-center"><%=email.email_attachments.length%></td>
            <td class="text-center"><%= email.send_at.strftime("%d/%m/%y à %H:%M") %></td>
		  		<%# Affichage des boutons d'action %>
			    	<td class="text-center dropdown">
					      <a class="dropdown-toggle" data-toggle="dropdown" href="#">
						    <%= '<i class="fa fa-bolt fa-2x action-icon"></i>'.html_safe %>
					      </a>
					      <ul class="dropdown-menu pull-right">
						    <li><%= link_to "Éditer", edit_email_path(email.id) %></li>
						    <li><%= link_to "Supprimer", email, :id => email.id, :confirm => 'Confirmer la suppression ?', :method => :delete %></li>

						    <%# Si l'email est "valide" (complet) alors on propose un bouton "traiter" qui lance la conversion %>
						    <% if email.is_convertible_to_events? %>
							    <li class="divider" style="margin: 2px;"></li>
							    <li><%= link_to "Traiter", {:controller => 'emails', :action => 'convert', :email => email} %></li>
						    <% end %>

					    </ul>
			      </td>
      		</tr>

	        <%# Affichage du lien vers les autres emails %>
			<% if current_user.emails.length > 5 %>
				<tr>
					<td colspan="9" class="text-center">
						<%= link_to('Afficher tout mes emails', emails_path, :title => 'Mes emails') %>
					</td>
				</tr>
        <%end%>
			<% end %>
		</tbody>
	</table>
</div>

app/views/notifications/_state.html.erb
<div class="container-fluid">
<% if @connection.active %>
    <div class="alert alert-info">
        Le module de conversion d'email en évènement est actuellement <strong>activé</strong>.<br/>
        Pour l'utiliser, il vous suffit d'ajouter à votre email l'adresse <strong><%= @connection.login %></strong> dans le champ "CCI" de votre client de messagerie.
    </div>
<% elsif !@connection.active %>
    <div class="alert alert-warning">
        Le module de conversion d'email en évènement est actuellement <strong>désactivé</strong>.<br/>
    </div>
<% end %>
</div>

app/views/notifications/_title.html.erb
<div class="container-fluid" style="margin-top: 1em;">
	<div class="well">
       <div class="row-fluid">
         <div class="span9">
			<h1><%= "<i class=\"fa fa-bell\"></i> #{t('app.model.NotificationCenter')}".html_safe %></h1>
         </div>
       </div>
     </div>
</div>

app/views/notifications/index.html.erb
<%= render 'title', :locals => { :title => @title }%>

<%= render 'state' %>
<% if @emails.length >= 1 %>
	<%= render 'emails' %>
<% else %>
	<center><h3>Pas de message à traiter</h3></center>
<% end %>

<%# puts "LONGUEUR : #{@tasks.length}" %>
<%# if @tasks.length >= 1 %>
	<%#= render 'tasks' %>
<%# end %>