config/routes.rb
Crm::Application.routes.draw do

  def set_route(pp, ps, c)
    match "#{pp}(.:format)",   :controller => c,  :action => 'index',     :via => :get,   :as => c
    match "#{pp}(.:format)",   :controller => c,  :action => 'create',    :via => :post,  :as => c
    match "#{ps}/new(.:format)",         :controller => c,  :action => 'new',       :via => :get,   :as => "new_#{c.singularize}"
    match "#{ps}/:id/edit(.:format)",    :controller => c,  :action => 'edit',      :via => :get,   :as => "edit_#{c.singularize}"
    match "#{ps}/:id(.:format)",         :controller => c,  :action => 'update',    :via => :put,   :as => "#{c.singularize}"
    match "#{ps}/:id(.:format)",         :controller => c,  :action => 'destroy',   :via => :delete, :as => "#{c.singularize}"
  end

  match 'attachment/:id(.:format)', to: 'attachments#destroy', via: :delete, as: :attachment

  match 'configuration', :controller => 'settings', :action => 'index', :via => :get, :as => 'settings'
  match 'configuration/update', :controller => 'settings', :action => 'update', :via => :post, :as => 'settings'

  match 'extractions/select_param_accounts', :controller=>'extractions', :action => 'select_param_accounts'
  match 'extractions/comptes', :controller=>'extractions', :action => 'accounts', :as => :csv, :via => :post
  match 'extractions/select_param_contacts', :controller=>'extractions', :action => 'select_param_contacts'
  match 'extractions/contacts', :controller=>'extractions', :action => 'contacts', :as => :csv

  match 'extractions/csv_backup', :controller=>'application', :action => 'send_csv_backup_file'
  match 'extractions/yaml_backup', :controller=>'application', :action => 'send_yaml_backup_file'

  match 'type-evenements(.:format)', to: 'eventTypes#index', via: :get, as: :event_types
  match 'type-evenements(.:format)', to: 'eventTypes#create', via: :post, as: :event_types
  match 'type-evenement/new(.:format)', to:'eventTypes#new', via: :get, as: :new_event_type
  match 'type-evenement/:id/edit(.:format)', to: 'eventTypes#edit', via: :get, as: :edit_event_type
  match 'type-evenement/:id(.:format)', to: 'eventTypes#update', via: :put, as: :event_type
  match 'type-evenement/:id(.:format)', to: 'eventTypes#destroy', via: :delete, as: :event_type

  match 'modele-devis(.:format)', to: 'quotationTemplates#index', via: :get, as: :quotation_templates
  match 'modele-devis(.:format)', to: 'quotationTemplates#create', via: :post, as: :quotation_templates
  match 'modele-devis/new(.:format)', to:'quotationTemplates#new', via: :get, as: :new_quotation_template
  match 'modele-devis/:id/edit(.:format)', to: 'quotationTemplates#edit', via: :get, as: :edit_quotation_template
  match 'modele-devis/:id(.:format)', to: 'quotationTemplates#update', via: :put, as: :quotation_template
  match 'modele-devis/:id(.:format)', to: 'quotationTemplates#destroy', via: :delete, as: :quotation_template

  resources :quotationLines

  set_route('devis', 'devis', 'quotations')
  match '/devis/filter(.:format)', :controller => 'quotations', :action => 'filter', :via => :get, :as => "filter_quotations_index"
  match '/devis/update_contact_select/:id', :controller=>'quotations', :action => 'update_contact_select'
  match '/devis/update_opportunity_select/:id', :controller=>'quotations', :action => 'update_opportunity_select'
  match '/devis/companies(.:format)', to: 'quotations#get_companies', via: :get
  match '/devis/contacts(.:format)', to: 'quotations#get_contacts', via: :get
  get '/devis/:id(.:format)', :controller => 'quotations', :action => 'show'
  set_route('relations', 'relation', 'relations')
  set_route('documents', 'document', 'documents')

  devise_for :user, :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' }, :controllers => { :registrations => 'registrations' }, :skip => [ :registrations, :sessions ]
  devise_scope :user do
    get '/login(.:format)',        :to => 'devise/sessions#new',        :as => :alt_new_user_session
	get '/user/login(.:format)',        :to => 'devise/sessions#new',        :as => :new_user_session
	post '/user/login(.:format)',       :to => 'registrations#session_new', :as => :user_session
    match '/user/logout(.:format)',          :to => 'devise/sessions#destroy', :via => Devise.mappings[:user].sign_out_via, :as => :destroy_user_session

    match '/users(.:format)', :controller => 'registrations', :action => 'index', :via => :get, :as => 'users'
    match '/user/:id/edit(.:format)', :controller => 'registrations', :action => 'edit', :via => :get, :as => 'edit_user'
    match '/user/new', :controller => 'registrations', :action => 'new', :via => :get, :as => 'new_user'
    match '/user/:id', :controller => 'registrations', :action => 'update', :via => :put, :as => 'user'
    match '/user/:id', :controller => 'registrations', :action => 'destroy', :via => :delete, :as => 'user'
    match '/users', :controller => 'registrations', :action => 'create', :via => :post, :as => 'users'
  end

  set_route('opportunites', 'opportunite', 'opportunities')
  match '/opportunites/update_contact_select/:id', :controller=>'opportunities', :action => 'update_contact_select'
  match '/opportunites/filter(.:format)', :controller => 'opportunities', :action => 'filter', :via => :get, :as => "filter_opportunity_index"

  set_route('origines', 'origine', 'origins');

  set_route('activites', 'activity', 'activities');

  set_route('categories_contrat', 'categorie_contrat', 'contract_categories');

  set_route('avancements_campagne', 'avancement_campagne', 'campaign_completed_stages');

  set_route('resultats_campagne', 'resultat_campagne', 'campaign_result_stages');

  set_route('campagnes', 'campagne', 'campaigns');

  set_route('contrats', 'contract', 'contracts');
  match '/contrats/filter(.:format)', :controller => 'contracts', :action => 'filter', :via => :get, :as => "filter_contracts_index"

  set_route('tags', 'tag', 'tags');

  set_route('modes_paiement', 'payment_mode', 'payment_modes');

  set_route('conditions_reglement', 'payment_term', 'payment_terms');

  match 'taches/update_contact_select/:id', :controller=>'tasks', :action => 'update_contact_select'

  set_route('taches', 'tache', 'tasks')
  match '/taches/filter(.:format)', :controller => 'tasks', :action => 'filter', :via => :get, :as => "filter_tasks_index"
  match '/tache/:id/finished', :controller=>'tasks', :action=>'finished', :as=>"finished_task"

  set_route('categories_compte', 'account_category', 'account_categories');

  set_route('type_evenement_email', 'mail_event_type', 'mail_event_types');
  
  match 'comptes/extract', controller: 'accounts', action: 'extract'
  match 'comptes/delete_tag', :controller=> 'accounts', :action =>'delete_tag'
  match 'comptes/doublons', controller: 'accounts', action: 'duplicates', :as => 'duplicate_accounts'
  match 'compte/:id/fusion/:id_to_merge', controller: 'accounts', action: 'merge', :via => :patch, :as => "merge_accounts"
  resources :accounts, :path => 'compte' do
    collection do
      get 'search'
      get 'search_tel'
      get 'update_tags'
      get 'filter'
      post 'add_tag'
    end
    resources :events, path: 'evenements'
    resources :tasks, path: 'taches'
    resources :opportunities, path: 'opportunites'
    resources :quotations, path: 'devis'
    resources :tags, path: 'tags'
    resources :documents, path: 'documents'
    resources :relations, path: 'relations'
    resources :contacts
    resources :contracts, path: 'contrats'
  end
  match 'comptes', :controller => 'accounts', :action => 'index'

  set_route('evenements', 'evenement', 'events')

  set_route('contacts', 'contact', 'contacts');
  match 'contacts/extract', controller: 'contacts', action: 'extract'
  match 'contacts/search(.:format)', :controller => 'contacts', :action => 'search', :via => :get, :as => "search_contact_index"
  match 'contacts/filter(.:format)', :controller => 'contacts', :action => 'filter', :via => :get, :as => "search_contact_index"

  root :to => 'home#index'

  match 'reporting', :controller => 'home', :action => 'reporting'

  match 'search_by_phone/:phone_number', :controller => 'home', :action => 'search_by_phone'

  resources :about

  put "webmail_connections/update"
	get "webmail_connections/edit"
	get "webmail_connections/check"

  set_route('emails', 'email', 'emails')
  get "emails/convert"
  put "email/update"

	set_route('notifications', 'notification', 'notifications')

  resources :imports do
    new do
      post 'accounts'
      post 'contacts'
    end
  end
  match 'download', :controller => 'imports', :action => 'download'

  resources :import_accounts
  match 'import_accounts/importing', :controller => 'import_accounts', :action => 'importing_accounts'
  match 'import_accounts/recalculate_duplicates', :controller=>'import_accounts', :action=>'recalculate_duplicates'
  match 'destroy_all_invalids_accounts', :controller=>'import_accounts', :action=>'destroy_all_invalids'

  resources :import_contacts
  match 'import_contacts/importing', :controller => 'import_contacts', :action => 'importing_contacts'
  match 'import_contacts/recalculate_duplicates', :controller=>'import_contacts', :action=>'recalculate_duplicates'
  match 'destroy_all_invalids_contacts', :controller=>'import_contacts', :action=>'destroy_all_invalids'

end

app/models/document.rb
##
# This class represents a readable file.
# It belongs to Account
#
class Document < ActiveRecord::Base

  resourcify

  belongs_to :account
  belongs_to :user
  belongs_to :author_user, :foreign_key => 'created_by', :class_name => 'User'
  belongs_to :editor_user, :foreign_key => 'updated_by', :class_name => 'User'

  paginates_per 10

    # Conservé pour le bon fonctionnement des migrations --> non utilisé
    has_attached_file :attach

    # Nouvelle gestion des pièces-jointes
    has_many :document_attachments, :dependent => :destroy
    accepts_nested_attributes_for :document_attachments, allow_destroy: true
    alias_attribute :attachments, :document_attachments

  validates :name,  :presence => true

  # Validation using global Settings
  # don't use validates_associated : it does not work ;)
  validates :account, :presence => true


  def author
    return author_user || User::default
  end

  def editor
    return editor_user || User::default
  end

  scope :by_account, lambda { |account| where("account_id = ?", account.id )unless account.nil? }
end

app/controllers/documents_controller.rb
# encoding: utf-8

##
# This class manage Document
#
class DocumentsController < ApplicationController
  load_and_authorize_resource
  before_filter :load_account, :load_settings, only: [:index, :filter]
  layout :current_layout

  ##
  # Show the full list of Document by paginate_by
  #
  # GET /documents
  # GET /documents.json
  def index
    @documents = documents.order('name').page(params[:page])

    flash.now[:alert] = "Pas de documents !" if @documents.empty?

    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @documents }
    end
  end

  ##
  # Render the page to create a new Document
  #
  def new
    @document = Document.new
    @document.account_id = params[:account_id]
    respond_to do |format|
      format.html  # new.html.erb
      format.json  { render :json => @document }
    end
  end

  ##
  # Process to add a new Document into the DB
  #
  def create
    @document = Document.new(params[:document])
    @document.created_by = current_user.id

		if @document.save
			e = Event.new({
				:account_id => @document.account_id,
				:created_by => current_user.id,
				:notes => "Document n°#{@document.id} créé\r\nNom : #{@document.name}\r\nDescription : #{@document.notes}",
				:user_id => current_user.id,
				:date_begin => Time.now,
				:date_end => Time.now })
			e.save
			redirect_to session.delete(:return_to) || account_events_url(@document.account_id), :notice => 'Le document a été créé'
		else
			render :action => "new"
		end
  end

  ##
  # Render the page to show one Document
  #
  def show
    @document = Document.find(params[:id])

    respond_to do |format|
      format.html  # show.html.erb
      format.json  { render :json => @document }
    end
  end

  ##
  # Render the page to edit an existing Document
  #
  def edit
    @document = Document.find(params[:id])
  end

  ##
  # Process to update an existing Document
  #
  def update
    @document = Document.find(params[:id])
    @document.updated_by = current_user.id

    respond_to do |format|
      if @document.update_attributes(params[:document])
        format.html  { redirect_to session.delete(:return_to) || account_events_url(@document.account_id) , :notice => 'Le document a ete mis a jour.' }
        format.json  { head :no_content }
      else
        flash[:error] = t('app.save_undefined_error')
        format.html  { render :action => "edit" }
        format.json  { render :json => @document.errors, :status => :unprocessable_entity }
      end
    end
  end

  ##
  # Process to destroy a document defined by this ID
  #
  def destroy
    @document = Document.find(params[:id])
    @document.destroy

    respond_to do |format|
      format.html { redirect_to session.delete(:return_to) || account_events_url(@document.account_id), :notice => "Le document a bien été supprimé." }
      format.json { head :no_content }
    end
  end

  private
    def load_account
      @account = Account.find_by_id(params[:account_id])
    end

    def load_settings
      #ClickToCall
      @setting = Setting.all.first
    end

    def documents
      @account ? @account.documents : Document
    end

    def current_layout
      if @account && @account.persisted? && request.path_parameters[:action] == "index" # i prefer helper 'current_action'
        "accounts_show"
      else
        "application"
      end
    end
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/views/documents/_form.html.erb
<%# encoding: utf-8 %>

<%# Récupération du des fonctions %>
<% content_for(:attachments_js) do %>
    <%= javascript_include_tag "attachments" %>
<% end %>

<% colon = t('app.fields.colon') %>
<%= nested_form_for(@document, :html => { :class => "well "}) do |f| %>
  <% if @document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
      <% @document.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="row row-fluid">
	<div class="field full">
		<div class="span2"><%= f.label(:name, t('app.fields.name') + colon) %></div>
		<p><%= f.text_field(:name ,{ :class => 'required' }) %><span class="req" /></p>
	</div>
</div>
<div class="row row-fluid">
	<div class="field full">
		<div class="span2"><%= f.label('account-search', t('app.model.Account') + colon) %></div>
<% company = ""
if !@document.account.nil?
	company = @document.account.company
end %>
		<p>
			<%= text_field_tag(nil, company, { :placeholder => 'Rechercher', :class => 'typeahead-account-search required', :type => 'search', :autocomplete => 'off', 'data-field' => 'account_id' }) %><span class='req' />
			<%= image_tag('/assets/icons/loading.gif', :alt => 'Please wait...', :class => 'loading hidden') %>
			<span class="label label-info" id="task_notice"  style="display: none; margin-left: 2em;">
				<i class="icon-warning-sign icon-white"></i> Un événement sera créé sur le compte correspondant
			</span>
		</p>
		<%= f.text_field :account_id, { :style => 'display: none; visible: none;', :id => 'account_id' } %>
	</div>
</div>

    <div id="attachments">
      <%= f.fields_for :document_attachments do |ta| %>
        <div class="row row-fluid">
          <div class="field full">
            <div class="span2"></div>
            <% if ta.object.new_record? %>
              <%= ta.file_field :attach, required: true %>
              <script>$ (":file").filestyle({buttonText: 'Choisir un fichier'});</script>
            <% else %>
              <%= link_to ta.object.attach_file_name, ta.object.attach.url %>
            <% end %>
            <%= ta.link_to_remove "", class: 'icon-remove' %>
          </div>
        </div>
      <% end %>
    </div>

    <div class="row row-fluid">
      <div class="field full">
        <div class="span2"></div><%= f.link_to_add raw('<i class="icon-plus"></i> Ajouter une pièce-jointe'), :document_attachments, data: { target: '#attachments' } %>
      </div>
    </div>

	<div class="row row-fluid">
		<div class="field full">
			<div class="span2"><%= f.label(:notes, t('app.fields.description')) %></div>
			<%= f.text_area :notes, :rows => "5", :style => 'width: 50%;' %>
		</div>
	</div>
	<div class="field">
    <% if !@document.id.nil? %>
		<div class="span9"> Créé par : <%= @document.author.full_name %>, le <%= @document.created_at.strftime("%d/%m/%y à %H:%M") %>. </div> <br />

		<% if !@document.updated_by.nil? %>
			<div class="span9"> Dernièrement modifié par : <%= @document.editor.full_name %>, le <%= @document.updated_at.strftime("%d/%m/%y à %H:%M") %>. </div> <br />

		<% else %>
		<% end %>

	<% end %>
	</div>

	<hr />

     <div class="row">
	  <%= if !@document.id.nil? then f.button 'Modifier le document', :type => :submit, :class =>"btn btn-primary",:id =>"document_submit_form" else f.button 'Créer un document', :type => :submit, :class =>"btn btn-primary",:id =>"document_submit_form" end %>
      <%= if !@document.id.nil? then link_to '<i class="fa fa-trash fa-lg"></i>'.html_safe, @document, :title => "Supprimer le document", :confirm => 'Confirmer la suppression ?', :class =>"pull-right btn", :method => :delete end %>
  </div>
<% end %>

app/views/documents/edit.html.erb
<div class="container-fluid">
   <div class="well" style="margin-top: 1em;">
      <div class="row-fluid">
         <div class="span9">
         <h1><%= "<i class=\"fa fa-folder\"></i>  #{t('app.actions.edition').capitalize} #{t('app.model.Document')}".html_safe %> n°<%= @document.id %></h1>
         </div>
          <%= link_to '<i class="fa fa-arrow-circle-left fa-3x action-icon"></i>'.html_safe, accounts_url ,{:title => "Retour", :class=>"pull-right"} %>
      </div>
   </div>

   <%= render 'form' %>
</div>

app/views/documents/index.html.erb
<div class="container-fluid" style="margin-top: 1em;">


     <div class="well">
       <div class="row-fluid">
         <div class="span8">
           <h2>Documents de <%= @account.company %></h2>
         </div>
           <%= link_to '<i class="fa fa-plus-circle fa-3x action-icon"></i>'.html_safe, new_account_document_path(:account_id => @account.id) ,{:title => "Créer un document", :class =>"pull-right"}%>
       </div>
     </div>


</div>


<div class="container-fluid">

 <% if Document.by_account(@account).blank? %>
 <h4> Aucun Document n'est rattaché à ce Compte </h4>
 <% else %>

 <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th class="text-center">Nom</th>
        <th class="text-center">Description</center></th>
	<th class="text-center">Fichiers joints</th>
        <th class="text-center">Éditer</th>
      </tr>
    </thead>
    <tbody>
      <% @documents = Document.by_account(@account).order('name ASC').page(params[:page]) %>
      <% @documents.each do |document| %>
        <tr>
         <td class="text-center"><%= document.name %></td>
         <td class="text-center"><%= truncate(document.notes, :length => 600, :separator => ' ') %></td>
         <td class="text-center">
         <% document.document_attachments.each do |attachment| %>
            <%= link_to attachment.attach_file_name , attachment.attach.url, :target => '_blank' %><br/>
         <% end %>
         </td>
         <td class="text-center"><%= link_to '<i class="fa fa-edit fa-2x action-icon"></i>'.html_safe, edit_document_path(document),{:title => "Éditer le document"} %></td>
        </tr>
        <% end %>
      </tbody>
  </table>

  <br />

  <%= paginate @documents %>

  <% end %>

</div>

app/views/documents/new.html.erb
<div class="container-fluid">

   <div class="well" style="margin-top: 1em;">
      <div class="row-fluid">
         <div class="span9">
           <h1><%= "<i class=\"fa fa-folder\"></i> #{t('app.default.new_male').capitalize} #{t('app.model.Document')}".html_safe %></h1>
         </div>
          <%= link_to '<i class="fa fa-arrow-circle-left fa-3x action-icon"></i>'.html_safe, :back ,{:title => "Retour", :class=>"pull-right"} %>
      </div>
   </div>

   <%= render 'form' %>
</div>