config/routes.rb
Crm::Application.routes.draw do

  def set_route(pp, ps, c)
    match "#{pp}(.:format)",   :controller => c,  :action => 'index',     :via => :get,   :as => c
    match "#{pp}(.:format)",   :controller => c,  :action => 'create',    :via => :post,  :as => c
    match "#{ps}/new(.:format)",         :controller => c,  :action => 'new',       :via => :get,   :as => "new_#{c.singularize}"
    match "#{ps}/:id/edit(.:format)",    :controller => c,  :action => 'edit',      :via => :get,   :as => "edit_#{c.singularize}"
    match "#{ps}/:id(.:format)",         :controller => c,  :action => 'update',    :via => :put,   :as => "#{c.singularize}"
    match "#{ps}/:id(.:format)",         :controller => c,  :action => 'destroy',   :via => :delete, :as => "#{c.singularize}"
  end

  match 'attachment/:id(.:format)', to: 'attachments#destroy', via: :delete, as: :attachment

  match 'configuration', :controller => 'settings', :action => 'index', :via => :get, :as => 'settings'
  match 'configuration/update', :controller => 'settings', :action => 'update', :via => :post, :as => 'settings'

  match 'extractions/select_param_accounts', :controller=>'extractions', :action => 'select_param_accounts'
  match 'extractions/comptes', :controller=>'extractions', :action => 'accounts', :as => :csv, :via => :post
  match 'extractions/select_param_contacts', :controller=>'extractions', :action => 'select_param_contacts'
  match 'extractions/contacts', :controller=>'extractions', :action => 'contacts', :as => :csv

  match 'extractions/csv_backup', :controller=>'application', :action => 'send_csv_backup_file'
  match 'extractions/yaml_backup', :controller=>'application', :action => 'send_yaml_backup_file'

  match 'type-evenements(.:format)', to: 'eventTypes#index', via: :get, as: :event_types
  match 'type-evenements(.:format)', to: 'eventTypes#create', via: :post, as: :event_types
  match 'type-evenement/new(.:format)', to:'eventTypes#new', via: :get, as: :new_event_type
  match 'type-evenement/:id/edit(.:format)', to: 'eventTypes#edit', via: :get, as: :edit_event_type
  match 'type-evenement/:id(.:format)', to: 'eventTypes#update', via: :put, as: :event_type
  match 'type-evenement/:id(.:format)', to: 'eventTypes#destroy', via: :delete, as: :event_type

  match 'modele-devis(.:format)', to: 'quotationTemplates#index', via: :get, as: :quotation_templates
  match 'modele-devis(.:format)', to: 'quotationTemplates#create', via: :post, as: :quotation_templates
  match 'modele-devis/new(.:format)', to:'quotationTemplates#new', via: :get, as: :new_quotation_template
  match 'modele-devis/:id/edit(.:format)', to: 'quotationTemplates#edit', via: :get, as: :edit_quotation_template
  match 'modele-devis/:id(.:format)', to: 'quotationTemplates#update', via: :put, as: :quotation_template
  match 'modele-devis/:id(.:format)', to: 'quotationTemplates#destroy', via: :delete, as: :quotation_template

  resources :quotationLines

  set_route('devis', 'devis', 'quotations')
  match '/devis/filter(.:format)', :controller => 'quotations', :action => 'filter', :via => :get, :as => "filter_quotations_index"
  match '/devis/update_contact_select/:id', :controller=>'quotations', :action => 'update_contact_select'
  match '/devis/update_opportunity_select/:id', :controller=>'quotations', :action => 'update_opportunity_select'
  match '/devis/companies(.:format)', to: 'quotations#get_companies', via: :get
  match '/devis/contacts(.:format)', to: 'quotations#get_contacts', via: :get
  get '/devis/:id(.:format)', :controller => 'quotations', :action => 'show'
  set_route('relations', 'relation', 'relations')
  set_route('documents', 'document', 'documents')

  devise_for :user, :path_names => { :sign_in => 'login', :sign_out => 'logout', :sign_up => 'register' }, :controllers => { :registrations => 'registrations' }, :skip => [ :registrations, :sessions ]
  devise_scope :user do
    get '/login(.:format)',        :to => 'devise/sessions#new',        :as => :alt_new_user_session
	get '/user/login(.:format)',        :to => 'devise/sessions#new',        :as => :new_user_session
	post '/user/login(.:format)',       :to => 'registrations#session_new', :as => :user_session
    match '/user/logout(.:format)',          :to => 'devise/sessions#destroy', :via => Devise.mappings[:user].sign_out_via, :as => :destroy_user_session

    match '/users(.:format)', :controller => 'registrations', :action => 'index', :via => :get, :as => 'users'
    match '/user/:id/edit(.:format)', :controller => 'registrations', :action => 'edit', :via => :get, :as => 'edit_user'
    match '/user/new', :controller => 'registrations', :action => 'new', :via => :get, :as => 'new_user'
    match '/user/:id', :controller => 'registrations', :action => 'update', :via => :put, :as => 'user'
    match '/user/:id', :controller => 'registrations', :action => 'destroy', :via => :delete, :as => 'user'
    match '/users', :controller => 'registrations', :action => 'create', :via => :post, :as => 'users'
  end

  set_route('opportunites', 'opportunite', 'opportunities')
  match '/opportunites/update_contact_select/:id', :controller=>'opportunities', :action => 'update_contact_select'
  match '/opportunites/filter(.:format)', :controller => 'opportunities', :action => 'filter', :via => :get, :as => "filter_opportunity_index"

  set_route('origines', 'origine', 'origins');

  set_route('activites', 'activity', 'activities');

  set_route('categories_contrat', 'categorie_contrat', 'contract_categories');

  set_route('avancements_campagne', 'avancement_campagne', 'campaign_completed_stages');

  set_route('resultats_campagne', 'resultat_campagne', 'campaign_result_stages');

  set_route('campagnes', 'campagne', 'campaigns');

  set_route('contrats', 'contract', 'contracts');
  match '/contrats/filter(.:format)', :controller => 'contracts', :action => 'filter', :via => :get, :as => "filter_contracts_index"

  set_route('tags', 'tag', 'tags');

  set_route('modes_paiement', 'payment_mode', 'payment_modes');

  set_route('conditions_reglement', 'payment_term', 'payment_terms');

  match 'taches/update_contact_select/:id', :controller=>'tasks', :action => 'update_contact_select'

  set_route('taches', 'tache', 'tasks')
  match '/taches/filter(.:format)', :controller => 'tasks', :action => 'filter', :via => :get, :as => "filter_tasks_index"
  match '/tache/:id/finished', :controller=>'tasks', :action=>'finished', :as=>"finished_task"

  set_route('categories_compte', 'account_category', 'account_categories');

  set_route('type_evenement_email', 'mail_event_type', 'mail_event_types');
  
  match 'comptes/extract', controller: 'accounts', action: 'extract'
  match 'comptes/delete_tag', :controller=> 'accounts', :action =>'delete_tag'
  match 'comptes/doublons', controller: 'accounts', action: 'duplicates', :as => 'duplicate_accounts'
  match 'compte/:id/fusion/:id_to_merge', controller: 'accounts', action: 'merge', :via => :patch, :as => "merge_accounts"
  resources :accounts, :path => 'compte' do
    collection do
      get 'search'
      get 'search_tel'
      get 'update_tags'
      get 'filter'
      post 'add_tag'
    end
    resources :events, path: 'evenements'
    resources :tasks, path: 'taches'
    resources :opportunities, path: 'opportunites'
    resources :quotations, path: 'devis'
    resources :tags, path: 'tags'
    resources :documents, path: 'documents'
    resources :relations, path: 'relations'
    resources :contacts
    resources :contracts, path: 'contrats'
  end
  match 'comptes', :controller => 'accounts', :action => 'index'

  set_route('evenements', 'evenement', 'events')

  set_route('contacts', 'contact', 'contacts');
  match 'contacts/extract', controller: 'contacts', action: 'extract'
  match 'contacts/search(.:format)', :controller => 'contacts', :action => 'search', :via => :get, :as => "search_contact_index"
  match 'contacts/filter(.:format)', :controller => 'contacts', :action => 'filter', :via => :get, :as => "search_contact_index"

  root :to => 'home#index'

  match 'reporting', :controller => 'home', :action => 'reporting'

  match 'search_by_phone/:phone_number', :controller => 'home', :action => 'search_by_phone'

  resources :about

  put "webmail_connections/update"
	get "webmail_connections/edit"
	get "webmail_connections/check"

  set_route('emails', 'email', 'emails')
  get "emails/convert"
  put "email/update"

	set_route('notifications', 'notification', 'notifications')

  resources :imports do
    new do
      post 'accounts'
      post 'contacts'
    end
  end
  match 'download', :controller => 'imports', :action => 'download'

  resources :import_accounts
  match 'import_accounts/importing', :controller => 'import_accounts', :action => 'importing_accounts'
  match 'import_accounts/recalculate_duplicates', :controller=>'import_accounts', :action=>'recalculate_duplicates'
  match 'destroy_all_invalids_accounts', :controller=>'import_accounts', :action=>'destroy_all_invalids'

  resources :import_contacts
  match 'import_contacts/importing', :controller => 'import_contacts', :action => 'importing_contacts'
  match 'import_contacts/recalculate_duplicates', :controller=>'import_contacts', :action=>'recalculate_duplicates'
  match 'destroy_all_invalids_contacts', :controller=>'import_contacts', :action=>'destroy_all_invalids'

end

app/models/tag.rb
##
# This class represents a product defined by a name and a description.
# It can have and belongs to many Account and Contacts
#
class Tag < ActiveRecord::Base
  resourcify

  validates :name, uniqueness: true

  has_and_belongs_to_many :accounts
  has_and_belongs_to_many :contacts
  belongs_to :author_user, :foreign_key => 'created_by', :class_name => 'User'
  belongs_to :editor_user, :foreign_key => 'updated_by', :class_name => 'User'

  paginates_per 10

  def author
    return author_user || User::default
  end

  def editor
    return editor_user || User::default
  end

  #scope :by_account_with_contacts, lambda { |account| where("account_id = ?", account.id) unless account.nil? }
  #scope :by_account_tags, lambda { |account| where("account_id = ?", account.id) unless account.nil? }
end

app/controllers/tags_controller.rb
# encoding: utf-8

class TagsController < ApplicationController


  #load_and_authorize_resource :account, :parent => false #this line is commented on 2014/11/18 to avoid bug on edit tags
  load_and_authorize_resource :tag, :through => :account, :shallow => true
  before_filter :authenticate_user!
  before_filter :load_account, :load_settings, only: [:index, :filter]

  layout :current_layout

  ##
  # Show the full list of Tags by pagination_by
  #
  # GET /tags
  # GET /tags.json
  def index
    @tags = tags.order('name').page(params[:page])

    flash.now[:alert] = "Pas de tags !" if @tags.empty?

    respond_to do |format|
      format.html  # index.html.erb
      format.json  { render :json => @produits }
    end
  end

  ##
  # Show the page with the form to add a new Tag
  #
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html  # new.html.erb
      format.json  { render :json => @tag }
    end
  end

  ##
  # Process to create a new Tag into the DB
  #
  def create
    @tag = Tag.new(params[:tag])
    @tag.created_by = current_user.id

    respond_to do |format|
      if @tag.save
        format.html  { redirect_to tags_path, :notice => 'Le tag a été créé.' }
        format.json  { render :json => @tag,
          :status => :created}
      else
        flash[:error] = t('app.save_undefined_error')
        format.html  { render :action => "new" }
        format.json  { render :json => @tag.errors,
          :status => :unprocessable_entity }
      end
    end
  end

  ##
  # Dispay the page to show one occurence of Tag
  #
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html  # show.html.erb
      format.json  { render :json => @tag }
    end
  end

  ##
  # Display the page with the form to edit one occurence of Tag
  #
  def edit
    @tag = Tag.find(params[:id])
  end

  ##
  # Process to save one occurence of Tag which is already exists
  #
  def update
    @tag = Tag.find(params[:id])
    @tag.updated_by = current_user.id

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html  { redirect_to(tags_url, :notice => 'Le tag a été mis à jour.') }
        format.json  { head :no_content }
      else
        flash[:error] = t('app.save_undefined_error')
        format.html  { render :action => "edit" }
        format.json  { render :json => @tag.errors, :status => :unprocessable_entity }
      end
    end
  end

  ##
  # Delete one occurence of Tag from the Database
  #
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url, :notice => 'Le tag a bien été supprimé.' }
      format.json { head :no_content }
    end
  end

  private
    def load_account
     if (params[:account_id].present? and !params[:account_id].to_s.blank?)
       @account = Account.find_by_id(params[:account_id])
     else
        @account = nil
      end
    end

    def load_settings
      #ClickToCall
      @setting = Setting.all.first
    end

    def tags
      @account ? @account.tags : Tag
    end

    def current_layout
      if @account && @account.persisted? && request.path_parameters[:action] == "index" # i prefer helper 'current_action'
        "accounts_show"
      else
        "application"
      end
    end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag, :html => { :class => "well "}) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this produit from being saved:</h2>
<!-- une variable dans un conditions if avec une variable d'instance ne semblant pas exister... à voir -->
      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <div class="span2">Libellé :</div><%= f.text_field :name,{ :class => 'required', :style=>'width: 30em;'} %><span class="req" />
  </div>
  <div class="field">
    <div class="span2">Description :</div>
    <%= f.text_area :description, :rows => "5", :style=>'width: 30em;' %>
  </div>

      <br />

	<div class="field">
    <% if !@tag.id.nil? %>
		<div class="span9"> Créé par : <%= @tag.author.full_name %>, le </strong><%= @tag.created_at.strftime("%d/%m/%y à %H:%M") %>. </div> <br />

		<% if !@tag.updated_by.nil? %>
			<div class="span9"> Dernièrement modifié par : <%= @tag.editor.full_name %>, le <%= @tag.updated_at.strftime("%d/%m/%y à %H:%M") %>. </div> <br />

		<% else %>
		<% end %>

	<% end %>
	</div>

	<hr />

   <div class="row">
   <%= if !@tag.id.nil? then f.button 'Modifier le tag', :type => :submit, :class =>"btn btn-primary",:id =>"tag_validate_form" else f.button 'Créer un tag', :type => :submit, :class =>"btn btn-primary",:id =>"tag_validate_form" end%>
   <%= if !@tag.id.nil? then link_to '<i class="fa fa-trash-o fa-lg"></i>'.html_safe, @tag, :title => "Supprimer le tag", :confirm => 'Confirmer la suppression ?', :class=>"pull-right btn", :method => :delete end %>
    </div>
  </div>
<% end %>

app/views/tags/_index.html.erb
<%= render 'title', :locals => { :title => @title }%>

<div class="container-fluid">

  <table class="table table-bordered table-striped">
    <thead>
      <tr>
        <th><center>#</center></th>
        <th><center>Nom</center></th>
        <th><center>Description</center></th>
        <th><center>Éditer</center></th>
      </tr>
    </thead>

  <tbody>
  <% @tags.each do |tag| %>
    <tr>
      <td><center><%= tag.id %></center></td>
      <td><center><%= tag.name %></center></td>
      <td><center><%= truncate(tag.description, :length => 75, :separator => ' ')%></center></td>
      <td><center><%= link_to '<i class="fa fa-edit fa-2x action-icon"></i>'.html_safe, edit_tag_path(tag),{:title => "Éditer le tag"} %></center></td>
    </tr>
  <% end %>
  </tbody>
  </table>

  <br />

  <%= paginate @tags %>

</div>

app/views/tags/_index_when_account.html.erb
<% @tags_select = Tag.all - @account.tags %>

<div class="container-fluid" style="margin-top: 1em;">


     <div class="well">
       <div class="row-fluid">
         <div class="span8">
           <h2>Tags de <%=@account.company%></h2>
         </div>
         </div>
       </div>
     </div>



<div class="container-fluid">
       <div class="row-fluid">
         <div class="span9">
          <%= form_tag({:controller => "accounts", :action => "add_tag", :account_id => @account.id}, :method => "post") do %>
            <%= select_tag :tag_id, options_from_collection_for_select(@tags_select, "id", "name") %>
						<% if (@tags_select.count > 0) %>
              <%= submit_tag "Affecter", class: "btn btn-primary" %>
						<% else %>
						  <%= label_tag(:tag_id, "Aucun tag disponible à l'ajout", { :class => 'badge badge-warning', :style => 'vertical-align: top; margin-left: 5px; margin-top: 6px;' }) %>
					  <% end %>
          <% end %>
          </div>
		</div>

	<% if @account.tags.blank? %>
		<h4> Aucun Tag n'est rattaché à ce compte...</h4>
	<% else %>



<table class="table table-bordered table-striped">
  <thead>
  <tr>
    <th class="text-center">Nom</th>
    <th class="text-center">Description</th>
    <th class="text-center">Actions</th>
  </tr>
  </thead>
  <tbody>


<% @tags.each do |tag| %>
  <tr>
    <td style="width: 15em;" class="text-center"><%= tag.name %></td>
    <td><%= truncate(tag.description, :length => 500, :separator => ' ') %></td>
    <td class="text-center"><%= link_to '<i class="fa fa-trash-o fa-2x action-icon"></i>'.html_safe, {:controller => "accounts", :action => "delete_tag", :account_id => @account.id, :tag_id => tag.id } %></td>
	<% end %>
  </tbody>
</table>

  <br />

  <%= paginate @tags %>


<% end %>
</div>

app/views/tags/_title.html.erb
<div class="container-fluid" style="margin-top: 1em;">
     <div class="well">
       <div class="row-fluid">
         <div class="span9">
			<h1><%= "<i class=\"fa fa-tags\"></i> #{t('app.model.Tags')}".html_safe %></h1>
         </div>
           <%= link_to '<i class="fa fa-plus-circle fa-3x action-icon"></i>'.html_safe, new_tag_path ,{:title => "Créer un tag", :class=>"pull-right"}%>
       </div>
     </div>


</div>

app/views/tags/edit.html.erb
<div class="container-fluid">

   <div class="well" style="margin-top: 1em;">
      <div class="row-fluid">
         <div class="span9">
			<h1><%= "<i class=\"fa fa-tags\"></i>  #{t('app.actions.edition').capitalize} #{t('app.model.Tag')}".html_safe %> n°<%= @tag.id %></h1>
         </div>
          <%= link_to '<i class="fa fa-arrow-circle-left fa-3x action-icon"></i>'.html_safe, :back ,{:title => "Retour", :class=>"pull-right"} %>
      </div>
   </div>

   <%= render 'form' %>
</div>

app/views/tags/index.html.erb
<%
  index = 'index'
  if @account
    index += '_when_account'
  end
%>

<%= render partial: index %>

app/views/tags/new.html.erb
<div class="container-fluid">

   <div class="well" style="margin-top: 1em;">
     <div class="row-fluid">
       <div class="span9">
		 <h1><%= "<i class=\"fa fa-tags\"></i>  #{t('app.default.new_male').capitalize} #{t('app.model.Tag')}".html_safe %></h1>
        </div>
          <%= link_to '<i class="fa fa-arrow-circle-left fa-3x action-icon"></i>'.html_safe, :back ,{:title => "Retour", :class=>"pull-right"}%>
     </div>
   </div>

<%= render 'form' %>
</div>